[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  # Set this to your backend base URL if you deploy an API
  # NEXT_PUBLIC_API_BASE_URL = "https://your-backend.example.com"

